public class AccountHelper {

   public static final String LOW_PRIORITY_VALUE = 'Low';
   public static final Integer LOW_ANNUAL_MAXVALUE = 50000;
   public static final String LOW_AGENT_NAME = 'Agent Loo';

   public static final String MED_PRIORITY_VALUE = 'Medium';
   public static final Integer MED_ANNUAL_MAXVALUE = 100000;
   public static final String MED_AGENT_NAME = 'Agent Med';

   public static final String HIGH_PRIORITY_VALUE = 'High';
   public static final String HIGH_AGENT_NAME = 'Agent HIj';

}